---
version: "3"
services:
  promag-redis:
    image: docker.io/library/redis:latest
    container_name: promag-redis
    hostname: redis
    restart: unless-stopped
    networks:
      - promag-network

  promag:
    image: localhost:5000/promag:latest
    container_name: promag
    hostname: promag
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - promag-redis
    networks:
      - promag-network
networks:
  promag-network:

