---
version: "3"
services:
  promag-redis:
    image: docker.io/library/redis:latest
    container_name: promag-redis
    hostname: redis
    restart: unless-stopped
    networks:
      promag-network:

  promag:
    image: registry.upended.duckdns.org/promag:latest
    container_name: promag
    hostname: promag
    restart: unless-stopped
    ports:
      - 9000:9000
    depends_on:
      - promag-redis
    networks:
      promag-network:
    environment:
      REDIS_HOST: redis

networks:
  promag-network:

